# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: var1
    type: string
    default: test

trigger: none
pool:
  vmImage: windows-latest

stages:
  - stage: deployinfra
    jobs:
      - deployment: RegisterDNS
        displayName: "Register DNS Records"
        environment: 
         name: Dev
         resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - script: echo ${{ parameters.var1 }}

              - task: CopyFiles@2
                inputs:
                 SourceFolder: '$(Build.SourcesDirectory)'
                 Contents: '**'
                 TargetFolder: 'c:\build\'


              
              - task: AzurePowerShell@5
                inputs:
                  azureSubscription: 'MCT'
                  ScriptType: 'InlineScript'
                  Inline: |
                    
                    # param(
                    #      [string]$guid,
                    #    [string]$DnsZoneName = 'test.zone'
                    #)
                    # DNS zone to be created inside $DnsZoneName
                    
                    $guid = '0f874c22-eb62-4441-9263-a831bc6e8135'
                    $DnsZoneName = 'test.zone'
                    Write-Output $DnsZoneName 
                    Write-Output 'output'
                    $guidDNSZoneName = $guid + "." + $DnsZoneName
                    # for stand-alone DNS server, not AD integrated
                    $guidDNSZoneFile = $guid + ".dns"
                    $rg = $guid + '.rg'
                    $VmPublicIpAddress = @{}   
                    $pend = Get-AzPrivateEndpoint -ResourceGroupName $rg
                    $nicIds = $pend.NetworkInterfaces.id
                    ForEach ($nicId in $nicIds){
                      $nic = Get-AzNetworkInterface -ResourceId $nicId
                      $VmPublicIpAddress.Add($nic.Tag.vm,$nic.IpConfigurations.PrivateIPAddress) 
                      }
                    Write-Output $VmPublicIpAddress

                    $VmPublicIpAddress.keys | ForEach-Object{
                      $message = '{0} has {1} public IP!' -f $_, $VmPublicIpAddress[$_]
                        Write-Output $message
                      }
                    ## Get info from Azure and register in onprem DNS
                    # create DNS zone for the environment
                    # Add-DnsServerPrimaryZone -Name $guidDNSZoneName -zonefile $guidDNSZoneFile
                    
                    # foreach ($DnsRecord in $DnsRecords){
                    #   Add-DnsServerResourceRecordA -ZoneName $guidDNSZoneName -Name $DnsRecord.vm -IPv4Address $DnsRecord.IP -computername localhost -CreatePtr   
                    # }
                    # list created records
                    Get-DnsServerResourceRecord -ZoneName $guidDNSZoneName -RRType A
                  azurePowerShellVersion: 'LatestVersion'





