
trigger: none

pool: 
  vmimage: windows-latest


variables:
  BoxName: Box1

  
steps: 

- powershell: $(BoxName) = newGuid().tostring()


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'radul (MCT)(1)(d8058b04-7da0-4499-b527-029c6d0158f7)'
    subscriptionId: 'd8058b04-7da0-4499-b527-029c6d0158f7'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'vnetbox/rg.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: rgname



- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'radul (MCT)(d8058b04-7da0-4499-b527-029c6d0158f7)'
    subscriptionId: 'd8058b04-7da0-4499-b527-029c6d0158f7'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'vnetbox/rg.json'
    overrideParameters: '-name $(BoxName)'
    deploymentMode: 'Incremental'