
trigger: none

pool: 
  vmimage: windows-latest


variables:


  
steps: 


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $guid = new-guid()
      write-host $guid








