# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!

  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'radul (MCT)(1)(d8058b04-7da0-4499-b527-029c6d0158f7)'
    subscriptionId: 'd8058b04-7da0-4499-b527-029c6d0158f7'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'vnetbox/rg.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: rgname