# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters: 
  - name: subscription
    type: string
     
  - name: dc
    displayName: Deploy DC?
    type: boolean
    default: true


trigger: none


pool:
  vmImage: windows-latest

stages:
  - stage: deployinfra
    jobs:
      - job: ARMDeploy
        displayName: "Deploy environment through ARM"
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: 'MCT'
              subscriptionId: ${{ parameters.subscription }}
              location: 'West Europe'
              templateLocation: 'Linked artifact'
              csmFile: 'arm/rg.json'
              deploymentMode: 'Incremental'
              deploymentOutputs: armOutputString
              deploymentName: 'CreateRG'

          - task: PowerShell@2
            inputs:
              filePath: 'scripts/ReadOutputParameters.ps1'
              arguments: '-armOutputString ''$(armOutputString)'''





          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'MCT'
              subscriptionId: ${{ parameters.subscription }}
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(Output_rgname)'
              location: 'West Europe'
              templateLocation: 'Linked artifact'
              csmFile: 'arm/virtualnetwork.json'
              overrideParameters: '-guid $(Output_guid)'
              deploymentMode: 'Incremental'

          - ${{ if eq(parameters.dc, true) }}:
            - template: azure-pipeline-template-vm.yml
              parameters:
                vmName: 'dc'
                vmIndex: '10'
                imageGallery: 'BoxImages'
                subscription: ${{ parameters.subscription }}
                rgname: '$(Output_rgname)'
                guid: '$(Output_guid)'