# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters: 
  - name: subscription
    type: string
     

trigger: none


pool:
  vmImage: windows-latest

stages:
  - stage: deployinfra
    jobs:
      - job: ResourceGroup
        displayName: "Create Resource Group"
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: 'MCT'
              subscriptionId: ${{ parameters.subscription }}
              location: 'West Europe'
              templateLocation: 'Linked artifact'
              csmFile: 'arm/rg.json'
              deploymentMode: 'Incremental'
              deploymentOutputs: $(armOutputString)

          - task: PowerShell@2
            inputs:
              filePath: 'scripts/ReadOutputParameters.ps1'
              arguments: '$(armOutputString)'



